all:
  hosts:
    node10-2:
      ansible_host: 10.10.1.2
      ip: 10.10.1.2
      access_ip: 10.10.1.2
    node10-3:
      ansible_host: 10.10.1.3
      ip: 10.10.1.3
      access_ip: 10.10.1.3
    master20-2:
      ansible_host: 10.20.1.2
      ip: 10.20.1.2
      access_ip: 10.20.1.2
    node40-2:
      ansible_host: 10.40.1.2
      ip: 10.40.1.2
      access_ip: 10.40.1.2
    node40-3:
      ansible_host: 10.40.1.3
      ip: 10.40.1.3
      access_ip: 10.40.1.3
  children:
    kube_control_plane:
      hosts:
        master20-2:
    kube_node:
      hosts:
        node10-2:
        node10-3:
        master20-2:
        node40-2:
        node40-3:
    etcd:
      hosts:
        node10-2:
        node10-3:
        master20-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
